#!/usr/bin/env python3
"""
Generate vault/architecture.md — a polished Mermaid flowchart of Lilo's
runtime architecture. Companion to the click-to-nav vault/architecture.canvas,
but optimized for "look at it" / screenshot.

Reads:
  - templates/team/.claude/agent-registry/*.md  (PM specialists, bucketed by category)
  - .claude/agents/  (orchestrator-only subagents)
  - .mcp.json  (project MCPs)
  - pipeline.json  (live projects, status-colored)

Outputs: ../vault/architecture.md

Notes:
  - Mermaid in Obsidian supports HTML in labels (<b>, <br/>, <sub>) when the
    note is rendered. Inline preview also renders these.
  - classDef colors are tuned for Obsidian's default dark theme. Light-theme
    contrast is OK but not the primary target.
"""

import json
from pathlib import Path


PM_CATEGORIES = {
    "Reviewers": [
        "code-reviewer", "code-simplifier", "python-reviewer",
        "typescript-reviewer", "security-reviewer", "silent-failure-hunter",
        "refactor-cleaner", "comment-analyzer", "type-design-analyzer",
    ],
    "Builders": [
        "code", "frontend", "scraper", "api-integrator",
        "data-pipeline", "db-designer", "devops", "ios-sim-driver",
    ],
    "Testing & Build": [
        "tdd-guide", "e2e-runner", "pr-test-analyzer",
        "build-error-resolver", "performance-optimizer",
    ],
    "Docs & Design": [
        "code-architect", "design-critic", "document-critic", "docs",
        "docs-lookup", "doc-updater", "a11y-architect", "seo-specialist",
        "lora-prompt-builder",
    ],
    "Meta": ["team-historian"],
}

ORCH_AGENTS = ["outbox-sweeper", "pipeline-syncer", "stitch-operator"]

MCP_LIST = [
    ("lilo-tools",    "MCP bridge"),
    ("playwright",    "headless browser"),
    ("ios-simulator", "Xcode iOS Simulator"),
    ("picarx",        "Stitch robot (SSE)"),
]

# Signature edges only — keep the network density low. These pick out the
# actually-meaningful MCP→specialist links.
MCP_SPECIALIST_EDGES = [
    ("picarx",        "stitch-operator"),
    ("ios-simulator", "ios-sim-driver"),
    ("playwright",    "scraper"),
    ("playwright",    "e2e-runner"),
    ("playwright",    "frontend"),
]


def slug(s: str) -> str:
    return s.replace("-", "_").replace(".", "_").replace(" ", "_").replace("&", "and")


def status_class(status: str) -> str:
    s = (status or "").lower().strip()
    if "block" in s:
        return "projBlocked"
    if "paus" in s:
        return "projPaused"
    if "complet" in s or "done" in s or "ready" in s:
        return "projDone"
    if "active" in s or "in_progress" in s:
        return "projActive"
    if "solo" in s:
        return "projSolo"
    return "projSolo"


def load_projects():
    p = Path("pipeline.json")
    if not p.exists():
        return []
    try:
        return json.loads(p.read_text()).get("projects", [])
    except Exception:
        return []


def render() -> str:
    projects = load_projects()
    L = []

    L.append("# Lilo — architecture")
    L.append("")
    L.append("> Generated by `scripts/render-architecture-mermaid.py`. "
             "Click any node to open its spec.")
    L.append("")
    L.append("```mermaid")
    L.append("%%{init: {")
    L.append("  'theme': 'base',")
    L.append("  'themeVariables': {")
    L.append("    'primaryColor': '#0e1820',")
    L.append("    'primaryTextColor': '#d9eaf0',")
    L.append("    'primaryBorderColor': '#3fbac2',")
    L.append("    'lineColor': '#5a7480',")
    L.append("    'fontFamily': 'ui-sans-serif, system-ui, sans-serif',")
    L.append("    'fontSize': '14px'")
    L.append("  }")
    L.append("}}%%")
    L.append("flowchart TD")
    L.append("")
    L.append('  lilo(["<b>Lilo</b><br/><sub>the orchestrator</sub>"]):::lilo')
    L.append("")

    # ── PM cluster (nested by category) ──────────────────────────────
    L.append('  subgraph PM["PM template — specialists"]')
    L.append("    direction TB")
    for cat, members in PM_CATEGORIES.items():
        cat_id = slug(cat)
        L.append(f'    subgraph {cat_id}["{cat}"]')
        L.append("      direction LR")
        for m in members:
            L.append(f'      {slug(m)}["{m}"]:::pm')
        L.append("    end")
    L.append("  end")
    L.append("")

    # ── Orchestrator subagents ───────────────────────────────────────
    L.append('  subgraph ORCH["Lilo\'s subagents"]')
    L.append("    direction TB")
    for a in ORCH_AGENTS:
        L.append(f'    {slug(a)}["{a}"]:::orch')
    L.append("  end")
    L.append("")

    # ── MCPs ─────────────────────────────────────────────────────────
    L.append('  subgraph MCP["MCPs"]')
    L.append("    direction TB")
    for name, blurb in MCP_LIST:
        L.append(f'    {slug(name)}["<b>{name}</b><br/><sub>{blurb}</sub>"]:::mcp')
    L.append("  end")
    L.append("")

    # ── Live projects ───────────────────────────────────────────────
    L.append('  subgraph PROJ["Active projects"]')
    L.append("    direction LR")
    for p in projects:
        name = p.get("name", "?")
        L.append(f'    {slug(name)}["{name}"]:::{status_class(p.get("status"))}')
    L.append("  end")
    L.append("")

    # ── Lilo → cluster edges ────────────────────────────────────────
    L.append("  lilo -- scaffolds --> PM")
    L.append("  lilo -- dispatches --> ORCH")
    L.append("  lilo -- uses --> MCP")
    L.append("  lilo -- tracks --> PROJ")
    L.append("")

    # ── Signature MCP → specialist edges ────────────────────────────
    pm_visible = {m for members in PM_CATEGORIES.values() for m in members}
    orch_visible = set(ORCH_AGENTS)
    mcp_visible = {n for n, _ in MCP_LIST}
    for src, dst in MCP_SPECIALIST_EDGES:
        if src in mcp_visible and (dst in pm_visible or dst in orch_visible):
            L.append(f"  {slug(src)} -. drives .-> {slug(dst)}")
    L.append("")

    # ── classDef theming ────────────────────────────────────────────
    L.append("  classDef lilo fill:#0b3a4a,stroke:#3fbac2,stroke-width:3px,color:#d9f5ff,font-weight:bold")
    L.append("  classDef pm fill:#102b1a,stroke:#5dc28a,stroke-width:2px,color:#d8f5d8")
    L.append("  classDef orch fill:#2e1f0b,stroke:#e09a40,stroke-width:2px,color:#fdebcd")
    L.append("  classDef mcp fill:#2e2710,stroke:#e0c45c,stroke-width:2px,color:#fdf5cd")
    L.append("  classDef projActive fill:#142b1a,stroke:#5dc28a,stroke-width:2px,color:#d8f5d8")
    L.append("  classDef projPaused fill:#2e2710,stroke:#e0c45c,stroke-width:2px,color:#fdf5cd")
    L.append("  classDef projBlocked fill:#3a1414,stroke:#e07070,stroke-width:2px,color:#ffdada")
    L.append("  classDef projDone fill:#221033,stroke:#a070e0,stroke-width:2px,color:#e8d8ff")
    L.append("  classDef projSolo fill:#0e1f2a,stroke:#7baac4,stroke-width:2px,color:#d0e8f5")
    L.append("")

    # ── click directives (open the spec file in Obsidian) ───────────
    for members in PM_CATEGORIES.values():
        for m in members:
            L.append(f'  click {slug(m)} "agents/{m}.md"')
    for a in ORCH_AGENTS:
        target = f"agents/{a}.md" if a == "stitch-operator" else f"orchestrator-agents/{a}.md"
        L.append(f'  click {slug(a)} "{target}"')
    for p in projects:
        n = p.get("name", "?")
        L.append(f'  click {slug(n)} "projects/{n}.md"')

    L.append("```")
    L.append("")
    L.append("---")
    L.append("")
    L.append("**Legend**")
    L.append("")
    L.append("- Cyan centerpiece → Lilo (the orchestrator)")
    L.append("- Green → PM specialists / active projects")
    L.append("- Orange → Lilo's own subagents")
    L.append("- Yellow → MCP servers / paused projects")
    L.append("- Red → blocked projects")
    L.append("- Purple → completed projects")
    L.append("- Blue → solo (no-PM) projects")
    L.append("")

    return "\n".join(L) + "\n"


def main():
    vault = Path("../vault")
    vault.mkdir(parents=True, exist_ok=True)
    out = vault / "architecture.md"
    out.write_text(render())
    print(f"Generated {out}")
    cluster_counts = (
        sum(len(v) for v in PM_CATEGORIES.values()),
        len(ORCH_AGENTS),
        len(MCP_LIST),
        len(load_projects()),
    )
    print(f"  PMs: {cluster_counts[0]}  Orch: {cluster_counts[1]}  MCPs: {cluster_counts[2]}  Projects: {cluster_counts[3]}")


if __name__ == "__main__":
    main()
